produits :
  - idEmplacement: 3
    paysDepart: "France"
    paysArrivee : "Belgique"
    couleur : "Bleu"
    taille : "S"
    reference : 27402
    score : A
    genre : "Femme"
    empreinte : 14.23
    idMagasin : 4
    idMarque : 2
    nomProduit : "Robe"