produits :
  - idEmplacement: 3
    paysDepart: "Portugal"
    paysArrivee : "Italie"
    couleur : "Jaune"
    taille : "M"
    reference : 28837
    score : A
    genre : "Enfant"
    empreinte : 16.23
    idMagasin : 2
    idMarque : 1
    nomProduit : "Pantalon cargo"